
target-version = "py312"
fix = true

[lint]
extend-select = [
    "B",
    "C90",
    # 360ERP: disable max line length for now, to prevent too many manual edits
    # on the introduction of pre-commit. Black will apply lenght 88 to most
    # lines anyway, so this only affects comments and text strings.
    # "E501",  # line too long (default 88)
    "I",  # isort
    "UP",  # pyupgrade
    "CPY",  # 360ERP: flake8-copyright
]
extend-safe-fixes = ["UP008"]
exclude = ["setup/*"]
# 360ERP: ignore "UP007 Use `X | Y` for type annotations" in pydantic models
ignore = ["UP007"]
preview = true  # 360ERP: required by flake-copyright

[format]
exclude = ["setup/*"]

[lint.per-file-ignores]
"__init__.py" = ["F401", "I001"]  # ignore unused and unsorted imports in __init__.py
"__manifest__.py" = ["B018"]  # useless expression

[lint.isort]
section-order = ["future", "standard-library", "third-party", "odoo", "odoo-addons", "first-party", "local-folder"]

[lint.isort.sections]
"odoo" = ["odoo"]
"odoo-addons" = ["odoo.addons"]

[lint.mccabe]
max-complexity = 16

[lint.flake8-copyright]
author = "360ERP"

# 360ERP: whitelisted fastapi default arguments
[lint.flake8-bugbear]
extend-immutable-calls = [
    "fastapi.Header",
    "fastapi.Depends",
    "fastapi.Security",
]
